# Postgres and Mailhog setup for Overte Directory Service testing

version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: directory_service
    ports:
      - "5432:5432"
    restart: unless-stopped

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 # SMTP Server
      - 8025:8025 # Web UI
